# Generated by Django 3.1.6 on 2022-03-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(blank=True, default='+91', max_length=4)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('favorite', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('Home', 'Home'), ('Personal', 'Personal'), ('Bussiness', 'Bussiness')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
            ],
        ),
    ]
