# Generated by Django 3.1.7 on 2022-03-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
